# Generated by Django 2.2 on 2021-04-10 09:02

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210403_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
