# Generated by Django 2.2 on 2021-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/20210403/avatar-1.jpg', upload_to='avatar/%Y%m%d/'),
        ),
    ]
